export const portfolio = [
  {
    id: '1',
    name: 'sonderescapes',
    website: 'https://sonderescapes.vercel.app',
    brandColor: '#11203d',
    title: 'Sonder Escapes',
    image: 'sonderescapes-icon',
    technology: 'Next.js, Firebase, Amadeus API, ChakraUI, Vercel',
    brief: [
      'SonderEscapes is a hotel searching platform, using the Amadeus API to source properties. The design is heavily inspired by Airbnb, with my own tweaks.',
      'A user can currently create a free account using Github oAuth powered by Firebase. Once a user has an account they can favourite hotels and view those favourite hotels. They can also see their account details and add a Date of Birth and gender.',
      'This is a work in progress.',
    ],
    images: [
      { name: 'sonderescapes1', alt: 'Sonder Escapes website homepage descktop screenshot' },
      { name: 'sonderescapes10', alt: 'Sonder Escapes website hompage mobile version screenshot' },
      { name: 'sonderescapes2', alt: 'Sonder Escapes website search results screenshot' },
      { name: 'sonderescapes3', alt: 'Sonder Escapes website hotel page top screenshot' },
      { name: 'sonderescapes8', alt: 'Sonder Escapes website hotel page image gallery screenshot' },
      {
        name: 'sonderescapes4',
        alt: 'Sonder Escapes website hotel page middle with map screenshot',
      },
      {
        name: 'sonderescapes5',
        alt: 'Sonder Escapes website hotel page bottom with options table screenshot',
      },
      { name: 'sonderescapes6', alt: 'Sonder Escapes website account page screenshot' },
      { name: 'sonderescapes7', alt: 'Sonder Escapes website personal profile screenshot' },
      { name: 'sonderescapes9', alt: 'Sonder Escapes website users favourites screenshot' },
    ],
  },
  {
    id: '2',
    name: 'mews',
    website: 'https://themewsretreat.vercel.app',
    title: 'The Mews Retreat',
    image: 'mews-icon',
    technology: 'Next.js, Sanity.io, ChakraUI, Vercel',
    brandColor: '#fe5a5e',
    brief: [
      "The Mews Retreat is a website for an Airbnb accommodation, showcasing the space and listing amenities in a way the owner wanted to represent the property. It's a very clean and simple design.",
      'The CMS is built with Sanity.io, as it is really intuitive for non-technical users, and has a powerful and hugely customisable CMS that works great with static websites.',
    ],
    images: [
      { name: 'mews1', alt: 'The Mews St Leonards welcome page screenshot' },
      { name: 'mews2', alt: 'The Mews St Leonards homepage section 2 screenshot' },
      { name: 'mews3', alt: 'The Mews St Leonards homepage section 3 screenshot' },
      { name: 'mews4', alt: 'The Mews St Leonards homepage footer screenshot' },
      { name: 'mews5', alt: 'The Mews St Leonards homepage menu open screenshot' },
      { name: 'mews6', alt: 'The Mews St Leonards inside amenities carousel screenshot' },
      { name: 'mews7', alt: 'The Mews St Leonards outside amenities carousel screenshot' },
      { name: 'mews8', alt: 'The Mews St Leonards backend cms homepage screenshot' },
      { name: 'mews9', alt: 'The Mews St Leonards backend cms homepage 2 screenshot' },
      { name: 'mews10', alt: 'The Mews St Leonards backend cms navigation screenshot' },
      { name: 'mews11', alt: 'The Mews St Leonards backend cms carousel screenshot' },
    ],
  },
];
