export const portfolio = [
  {
    id: '1',
    name: 'sonderescapes',
    website: 'https://sonderescapes.vercel.com',
    title: 'Sonder Escapes',
    image: 'sonderescapes-icon',
    technology: 'Next.js, Firebase, Amadeus API, ChakraUI, Vercel',
    brief: [
      'SonderEscapes is a hotel searching platform, using the Amadeus API to source properties. The design is heavily inspired by Airbnb, with my own tweaks.',
      'A user can currently create a free account using Github oAuth powered by Firebase. Once a user has an account they can favourite hotels and view those favourite hotels. They can also see their account details and add a Date of Birth and gender.',
      'This is a work in progress.',
    ],
    images: [
      'sonderescapes1',
      'sonderescapes10',
      'sonderescapes2',
      'sonderescapes3',
      'sonderescapes4',
      'sonderescapes5',
      'sonderescapes6',
      'sonderescapes7',
      'sonderescapes8',
      'sonderescapes9',
    ],
  },
  {
    id: '2',
    name: 'mews',
    website: 'https://themewsretreat.vercel.com',
    title: 'The Mews Retreat',
    image: 'mews-icon',
    technology: 'Next.js, Sanity.io, ChakraUI, Vercel',
    brief: [
      "The Mews Retreat is a website for an Airbnb accommodation, showcasing the space and listing amenities in a way the owner wanted to represent the property. It's a very clean and simple design.",
      'The CMS is built with Sanity.io, as it is really intuitive for non-technical users, and has a powerful and hugely customisable CMS that works great with static websites.',
    ],
    images: [
      'mews1',
      'mews2',
      'mews3',
      'mews4',
      'mews5',
      'mews6',
      'mews7',
      'mews8',
      'mews9',
      'mews10',
      'mews11',
    ],
  },
];
