export const portfolio = [
  {
    id: '0',
    name: 'eadee',
    website: 'https://eadee.co',
    brandColor: '#f4a261',
    title: 'EadeeCo',
    image: 'eadee-icon',
    technology:
      'React, Next.js, PostgreSQL, Strapi CMS, Styled Components, Vercel, AWS (EC2, RDS, S3 bucket)',
    brief: [
      'Eadee is an Employee Directory SaaS. It is built using a number of technologies, the brochure website is built on React, the Next.js framework deployed on Vercel. Strapi is used for the CMS hosted on AWS with webhooks in place for deployment from Github when the main branch is updated.',
      'The application is also built on Next.js and deployed through Vercel. It uses PostgreSQL as the database which is hosted on Heroku. I used Styled components throughout both the website and application.',
    ],
    images: [
      { name: 'eadee', alt: 'Eadee website screenshot' },
      { name: 'eadee1', alt: 'Eadee website screenshot' },
      { name: 'eadee2', alt: 'Eadee website screenshot' },
      { name: 'eadee3', alt: 'Eadee website screenshot' },
      { name: 'eadee8', alt: 'Eadee website screenshott' },
      {
        name: 'eadee4',
        alt: 'Eadee website screenshot',
      },
      {
        name: 'eadee5',
        alt: 'Eadee website screenshot',
      },
      { name: 'eadee6', alt: 'Eadee website screenshot' },
      { name: 'eadee7', alt: 'Eadee website screenshot' },
      { name: 'eadee9', alt: 'Eadee website screenshot' },
    ],
  },
  {
    id: '1',
    name: 'sonderescapes',
    website: 'https://sonderescapes.vercel.app',
    brandColor: '#11203d',
    title: 'Sonder Escapes',
    image: 'sonderescapes-icon',
    technology: 'React, Next.js, Firebase, Amadeus API, ChakraUI, Vercel',
    brief: [
      'SonderEscapes is a hotel searching platform, using the Amadeus API to source properties. The design is heavily inspired by Airbnb, with my own tweaks.',
      'A user can currently create a free account using Github oAuth powered by Firebase. Once a user has an account they can favourite hotels and view those favourite hotels. They can also see their account details and add a Date of Birth and gender.',
      'This is a work in progress.',
    ],
    images: [
      { name: 'sonderescapes1', alt: 'Sonder Escapes website homepage descktop screenshot' },
      { name: 'sonderescapes10', alt: 'Sonder Escapes website hompage mobile version screenshot' },
      { name: 'sonderescapes2', alt: 'Sonder Escapes website search results screenshot' },
      { name: 'sonderescapes3', alt: 'Sonder Escapes website hotel page top screenshot' },
      { name: 'sonderescapes8', alt: 'Sonder Escapes website hotel page image gallery screenshot' },
      {
        name: 'sonderescapes4',
        alt: 'Sonder Escapes website hotel page middle with map screenshot',
      },
      {
        name: 'sonderescapes5',
        alt: 'Sonder Escapes website hotel page bottom with options table screenshot',
      },
      { name: 'sonderescapes6', alt: 'Sonder Escapes website account page screenshot' },
      { name: 'sonderescapes7', alt: 'Sonder Escapes website personal profile screenshot' },
      { name: 'sonderescapes9', alt: 'Sonder Escapes website users favourites screenshot' },
    ],
  },
  {
    id: '2',
    name: 'mews',
    website: 'https://themewsretreat.vercel.app',
    title: 'The Mews Retreat',
    image: 'mews-icon',
    technology: 'React, Next.js, Sanity.io, ChakraUI, Vercel',
    brandColor: '#fe5a5e',
    brief: [
      "The Mews Retreat is a website for an Airbnb accommodation, showcasing the space and listing amenities in a way the owner wanted to represent the property. It's a very clean and simple design.",
      'The CMS is built with Sanity.io, as it is really intuitive for non-technical users, and has a powerful and hugely customisable CMS that works great with static websites.',
    ],
    images: [
      { name: 'mews1', alt: 'The Mews St Leonards welcome page screenshot' },
      { name: 'mews2', alt: 'The Mews St Leonards homepage section 2 screenshot' },
      { name: 'mews3', alt: 'The Mews St Leonards homepage section 3 screenshot' },
      { name: 'mews4', alt: 'The Mews St Leonards homepage footer screenshot' },
      { name: 'mews5', alt: 'The Mews St Leonards homepage menu open screenshot' },
      { name: 'mews6', alt: 'The Mews St Leonards inside amenities carousel screenshot' },
      { name: 'mews7', alt: 'The Mews St Leonards outside amenities carousel screenshot' },
      { name: 'mews8', alt: 'The Mews St Leonards backend cms homepage screenshot' },
      { name: 'mews9', alt: 'The Mews St Leonards backend cms homepage 2 screenshot' },
      { name: 'mews10', alt: 'The Mews St Leonards backend cms navigation screenshot' },
      { name: 'mews11', alt: 'The Mews St Leonards backend cms carousel screenshot' },
    ],
  },
];
